version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviewlens
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reviewlens
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGIN=http://localhost:5173
      - PORT=8787
    ports:
      - "8787:8787"
  frontend:
    working_dir: /app
    image: node:20
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8787
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  db_data:
